FROM gcr.io/google.com/cloudsdktool/google-cloud-cli:latest
RUN echo '[Credentials]' > .boto
RUN echo 'aws_access_key_id = $AWS_ACCESS_KEY' >> .boto
RUN echo 'aws_secret_access_key = $AWS_SECRET_ACCESS_KEY' >> .boto
